# Generated by Django 5.2.4 on 2025-08-10 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст цитаты')),
                ('author', models.CharField(verbose_name='Источник')),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Вес цитаты')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
