# Generated by Django 5.2.4 on 2025-08-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_love_laugh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.CharField(default='ixslea', verbose_name='Ваше имя'),
        ),
    ]
