# Generated by Django 5.2.4 on 2025-08-11 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_love_laugh', '0002_quote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='source',
            field=models.CharField(default='Винкс', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(default='ixslea', verbose_name='Ваше имя'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_love_laugh.quote')),
            ],
        ),
    ]
