# Generated by Django 5.2.4 on 2025-08-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_love_laugh', '0003_remove_quote_user_quote_likes_quote_source_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['quote', 'session_key'], name='live_love_l_quote_i_99d930_idx'),
        ),
    ]
