# Generated by Django 5.2.4 on 2025-08-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_love_laugh', '0004_like_live_love_l_quote_i_99d930_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(unique=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('text', 'source'), name='unique_quote_per_source'),
        ),
    ]
