# Generated by Django 5.2.4 on 2025-08-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_love_laugh', '0005_alter_quote_text_quote_unique_quote_per_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quote',
            name='unique_quote_per_source',
        ),
        migrations.AddField(
            model_name='quote',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
