# Generated by Django 5.2.4 on 2025-08-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_love_laugh', '0006_remove_quote_unique_quote_per_source_quote_views'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='like',
            name='live_love_l_quote_i_99d930_idx',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('quote', 'session_key')},
        ),
    ]
